apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: dlpg2ckmo-python
  janus-idp.io/tekton: dlpg2ckmo-python
  backstage.io/kubernetes-id: dlpg2ckmo-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: dlpg2ckmo-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
